### ISSUE TITLE
Non-FOSS in F-Droid build

### ISSUE THREAD

**Issue by licaon-kter** [BlazeCodeDev/TSViewer#3]
ref: https://github.com/BlazeCodeDev/TSViewer/blob/V1.4/app/build.gradle#L67

ref: https://github.com/BlazeCodeDev/TSViewer/blob/V1.4/app/build.gradle#L104

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/3386086237#L290

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.blazecode.tsviewer.yml

**Comment by BlazeCodeDev** [comment]
Thanks for the heads up! That's got to do with the new added wear os support. Unfortunately there is no other way of communicating between watch and phone.

**Comment by licaon-kter** [comment]
Yup, maybe add a `libre` flavor that does not need that?

**Comment by BlazeCodeDev** [comment]
I'll think about how to fix that, thanks!

**Comment by BlazeCodeDev** [comment]
Done, introduced new `foss` flavor with release [V2.0](https://github.com/BlazeCodeDev/TSViewer/releases/tag/V2.0)
