### ISSUE TITLE
[Feature Request]: Reverse Utilization graph

### ISSUE THREAD

**Issue by Windows200000** [BlazeCodeDev/TSViewer#5]
### Problem relation

The graph going left to right is unintuitive for me.

### Solution / Feature

Add an option to switch it around.

**Comment by BlazeCodeDev** [comment]
Thanks for the request. I've added it to my list. This will be included in the next update.

**Comment by BlazeCodeDev** [comment]
Fixed with [release V2.1.0](https://github.com/BlazeCodeDev/TSViewer/releases/tag/V2.1.0)
